#experiment_name: "swin_unet_ef"
#dataset_root: "./data/echonet_peds"
#save_dir: "./checkpoints"
#split_csv: ""
#window: 8
#batch_size: 1
#num_epochs: 10
#lr: 1e-4
#weight_decay: 5e-5
#loss: "masked_bce"
#num_workers: 8
#image_size: 224
#pretrained: true
#amp: true
#seed: 42
#processed_filelist: "Processed_FileList_mini.csv"



experiment_name: "swin_unet_finetune_on_dynamic_video"
dataset_root: "./data/echonet_peds"
processed_filelist: "Processed_dynamic_FileList.csv"
save_dir: "./checkpoints_finetune" 
initial_ckpt_path: "checkpoints_finetune/best_model_finetuned.pt"
window: 8 
batch_size: 1 
num_epochs: 30
lr: 5e-6
weight_decay: 1e-5
warmup_epochs: 3 
num_workers: 8
image_size: 224
pretrained: false 
amp: true
seed: 42